version: '3.8'

services:
  app:
    container_name: app
    build: 
      context: "./app" # lokasi path dari dockerfile
      dockerfile: Dockerfile # nama dockerfile
    # image yang dibuild dari docker compose tidak akan terhapus saat docker compose down, jadi harus dihapus secara manual
    image: "app-golang:1.0.0"
    environment:
      - "APP_PORT=8080"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s