version: '3.8'

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: naufal
      MONGO_INITDB_ROOT_PASSWORD: naufal
      MONGO_INITDB_DATABASE: admin
    networks:
      - mongo-networks

  mongo-express-example:
    image: mongo-express:latest
    container_name: mongo-express-example
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: naufal
      ME_CONFIG_MONGODB_ADMINPASSWORD: naufal
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    networks:
      - mongo-networks
    depends_on:
      - mongodb-example

networks:
  mongo-networks:
    driver: bridge
    name: mongo-networks